#!/bin/bash
echo "Uninstalling AEScrypt"
echo "Removing user directory"
sudo rm -rf ~/.aescrypt
echo "Removing binary files"
sudo rm /usr/local/bin/aes
echo "Removing config files"
sudo rm -rf /etc/aescrypt
echo "Done!"
